project: 
  type: website

website:
  title: "Chidera Orizu Bioinformatics/data science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  site-url: https://byuidatascience.github.io/course_work_portfolio/
  repo-url: https://github.com/byuidatascience/course_work_portfolio
  issue-url: https://github.com/byuidatascience/course_work_portfolio/issues/new
  repo-actions: [issue]

  page-footer: 
    border: true
    left: "Chidera Orizu 2025Â©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/chidera-orizu-8b5662250/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects

  sidebar:
    - title: "Projects"
      style: "docked"
      background: light
      contents:
        - text: "Projects"
          file: projects/consulting.Rmd
        - text: "---"
        - text: "Project 1"
          file: projects/MyChiSquaredTest.Rmd
        - text: "---"

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



